name: 'Test actions'
description: 'Test'
inputs:
  language:
    description: 'Language'
    required: false
    default: 'ja'
  cron_file:
    description: 'Crontab File'
    required: false
  cron_string:
    description: 'Crontab Content'
    required: false
  relative_path_base_dir:
    description: 'Base directory for relative paths'
    required: false
    default: ${{ github.workspace }}
  task_dirs:
    description: 'Script directory(comma splitted)'
    required: false
    default:  ''
  output_filename:
    description: 'File name of the output markdown'
    required: false
    default: ''
  rewrite_whitelist_path_from:
    description: 'Set to rewrite the white list basepath'
    required: false
    default: ''
  rewrite_whitelist_path_to:
    description: 'Set to rewrite the white list basepath'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
