name: Build and Publish npm packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://npm.pkg.github.com

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build

      - run: npm publish
        working-directory: ./packages/cron2docs-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
